# Generated by Django 2.0.5 on 2018-05-30 13:46

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cert',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('time_of_creation', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(blank=True, max_length=50)),
                ('email', models.CharField(blank=True, max_length=50)),
                ('file_path', models.CharField(blank=True, max_length=50)),
                ('uuid', models.CharField(blank=True, max_length=50, null=True)),
                ('cert_type', models.CharField(blank=True, max_length=50)),
                ('year', models.CharField(blank=True, max_length=4)),
            ],
        ),
    ]
